services:
  shopify_backend_node:
    container_name: shopify_custom_tags
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - SHOPIFY_SHOP_NAME=${SHOPIFY_SHOP_NAME}
      - SHOPIFY_STORE_URL=${SHOPIFY_STORE_URL}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_PASSWORD=${SHOPIFY_API_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped